export class Personalloan {
    ID:number
    CLIENT_ID:number
    PROPOSAL_ID:number
    PURPOSE_OF_LOAN:string
    INSURANCE_COMPANY_NAME: string
    INSURANCE_POLICY_AMOUNT: number
    INSURANCE_POLICY_END_DATE: any
    INSURANCE_POLICY_NUMBER: number
    INSURANCE_POLICY_TAKEN_DATE: any
    INSURANCE_SURRENDER_AMOUNT: number
    IS_INSURANCE_TAKEN: boolean =false
    IS_RECEIPT_OF_PAYMENT=0
}
